/**
 * Resolve Lucide icon component dari string name yang disimpan di DB (`menus.icon`).
 *
 * Whitelist explicit supaya bundle Vite hanya include icon yang benar-benar
 * dipakai (tree-shake friendly). Tambah icon di sini saat menu baru ditambah.
 */
import {
    Activity,
    BarChart3,
    BookOpen,
    Boxes,
    Building2,
    Calendar,
    CalendarClock,
    CalendarDays,
    ClipboardList,
    Cog,
    CreditCard,
    Database,
    Factory,
    FileBarChart,
    FileMinus,
    FileText,
    Hash,
    History,
    Inbox,
    Landmark,
    Layers,
    LayoutDashboard,
    LineChart,
    LogIn,
    MapPin,
    Menu,
    MessageCircle,
    Package,
    PackageOpen,
    ReceiptText,
    Settings,
    Settings2,
    Shield,
    ShoppingBag,
    ShoppingCart,
    Sliders,
    Smartphone,
    Store,
    Tag,
    Trash2,
    TrendingUp,
    Truck,
    Undo,
    Undo2,
    User,
    UserCog,
    Users,
    Wallet,
    Lock,
} from '@lucide/vue';

const MAP = {
    Activity,
    BarChart3,
    BookOpen,
    Boxes,
    Building2,
    Calendar,
    CalendarClock,
    CalendarDays,
    ClipboardList,
    Cog,
    CreditCard,
    Database,
    Factory,
    FileBarChart,
    FileMinus,
    FileText,
    Hash,
    History,
    Inbox,
    Landmark,
    Layers,
    LayoutDashboard,
    LineChart,
    LogIn,
    MapPin,
    Menu,
    MessageCircle,
    Package,
    PackageOpen,
    ReceiptText,
    Settings,
    Settings2,
    Shield,
    ShoppingBag,
    ShoppingCart,
    Sliders,
    Smartphone,
    Store,
    Tag,
    Trash2,
    TrendingUp,
    Truck,
    Undo,
    Undo2,
    User,
    UserCog,
    Users,
    Wallet,
    Lock,
};

export function iconFor(name, fallback = null) {
    if (!name) return fallback;
    return MAP[name] ?? fallback;
}
